services:
  mysql:
    build:
      context: ./resources/docker/mysql
    image: mysql-server:latest
    container_name: project-db
    environment:
      MYSQL_DATABASE: apidb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Adm1ns
      MYSQL_ROOT_PASSWORD: Adm1ns
    ports:
      - "3306:3306"
    restart: always
  php:
    build:
      context: ./resources/docker/php
    image: php-server:latest
    container_name: project-api
    ports:
      - "80:80"
    volumes:
      - ${PWD}:/var/www/html
    links:
      - mysql
